* About
This is a custom archlinux live-usb mainly meant for setting up encrypted
installations. This uses [[swaywm.org/][sway]] and [[https://github.com/thestinger/termite][termite]], for maximum cross compatibility.

** Methodology
Instead of using the standard ~archiso~ package, since I required AUR packages
and preferred an offline installation, this uses [[https://wiki.archlinux.org/index.php/Archiso_offline][archiso-offline]].

** Software Included
The exact list of packages added is present in ~packages.x86_64~
The basic end-user packages and the intended usage is described here.
** Size
Just cuz I can, this lists the size as I make changes:

| Package            | Size (MB) |
| base               |     ~ 567 |
| +veracrypt         |       688 |
| +networkmanager    |       695 |
| +chrony            |       695 |
| +tmux              |       695 |
| +reflector         |       695 |
| +caja              |       707 |
| +gnome_backgrounds |       732 |
| release_I          |       894 |
| +videoDrivers      |       903 |

** Configuration
*** Pacman
The pacman mirrors are generated with ~reflector~.
*** Chrony
This is configured to work with a dispatcher script.

*** AUR
The aur packages need to be configured in the main hzLinux folder as well as the
work folder.
These should work on the system, not relative to the liveUSB root.
** TODO List
*** [ ] Add gparted
*** [ ] Add more docs
* Release I
Roughly ~903MB~.
** Features
- LightDM + Aether Theme
- Default user (hzlinarch:hzlinarh)
- AUR helper (yay)
- Sway (master, wlroots)
- Caja
- Termite (noscd, wayland)
- Veracrypt
- gParted

* Release I-A
Around *1.1GB*.
** Features
- Fonts
- i3status-rust
- Smplayer (+skins)
- Zathura (+plugins)
- Audio (pulseaudio+plugins)
- Music (mpd, ncmpc, pianobar, audacious)
- Proxy (proxychains, windscribe)
- Screenshots (slurp+grim)
- Bluetooth (blueberry)
